### ISSUE TITLE
Bugs de la versión preliminar de escritorio

### ISSUE THREAD

**Issue by Dani-gr** [carloscmor/PRIMERA_FILA#13]
- [x] Pierdes cuando tienes -1 vidas, o 0 y respondes correctamente (pierdes al responder la siguiente pregunta). 
- [x] Si no le das a tirar después de una casilla especial de pregunta "experto", puedes "farmear" preguntas en la misma casilla.
   (Actualización: vale en cualquier casilla especial, y te quedas estancado en esa casilla sin poder avanzar, saliendo siempre la misma pregunta). *
- [x] A veces puedes seguir jugando cuando te quedas sin vidas.

*Adjunto posible causa: 
`Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 20 out of bounds for length 20`
	`[...]`
	`at java.base/java.util.ArrayList.get(ArrayList.java:427)`
	`at GUI.Controlador.actionPerformed(Controlador.java:229)`
	`[...]`

**Comment by Dani-gr** [comment]
Después del commit [032443c](https://github.com/carloscmor/PRIMERA_FILA/commit/032443ccaa06f44c75045cd4dc00f1104c2eef13):

- [ ] Sigues pudiendo "farmear" preguntas al caer en casillas especiales. Además, si el efecto no es pregunta experto, no se muestra de forma visual (de fondo sí). 
- [ ] Las dificultades no se asignan adecuadamente siempre (ejemplo: selecciono difficult en el desplegable, el tablero es medium (las preguntas son medium)).
- [ ] No debería darse pregunta en las casillas especiales cuyo efecto no sea "Pregunta experto" (si se da, hay pregunta, pide que tires, y se da el efecto y no la tirada (probablemente problema de la gui, no interno)).

**Comment by Dani-gr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Resolución de bugs](https://trello.com/c/6gsNocMC/88-resoluci%C3%B3n-de-bugs)
